"""redis

Revision ID: 9d477baea917
Revises: b3e1a064cf60
Create Date: 2024-11-05 18:06:31.174952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d477baea917'
down_revision: Union[str, None] = 'b3e1a064cf60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('uuid', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'uuid')
    # ### end Alembic commands ###
