"""delete

Revision ID: b3e1a064cf60
Revises: 3f8dfcd45744
Create Date: 2024-11-03 18:39:09.816085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e1a064cf60'
down_revision: Union[str, None] = '3f8dfcd45744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_image_tags_tag_id_tags', 'image_tags', type_='foreignkey')
    op.drop_constraint('fk_image_tags_image_id_images', 'image_tags', type_='foreignkey')
    op.create_foreign_key(op.f('fk_image_tags_image_id_images'), 'image_tags', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_image_tags_tag_id_tags'), 'image_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_image_tags_tag_id_tags'), 'image_tags', type_='foreignkey')
    op.drop_constraint(op.f('fk_image_tags_image_id_images'), 'image_tags', type_='foreignkey')
    op.create_foreign_key('fk_image_tags_image_id_images', 'image_tags', 'images', ['image_id'], ['id'])
    op.create_foreign_key('fk_image_tags_tag_id_tags', 'image_tags', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###
